[pytest]
addopts = --browser chromium --headed --slowmo 500 --html=reports/report.html --self-contained-html --tracing on --video on
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    security: Security tests
    api: API tests
