import pytest
from playwright.sync_api import Page
import os
from datetime import datetime
from components.ai_service import AIService

# Initialize AI Service
ai_service = AIService()

@pytest.fixture(autouse=True)
def capture_logs(page: Page):
    """Fixture to capture console logs and network errors during test execution."""
    logs = {"console": [], "network_errors": []}
    page.on("console", lambda msg: logs["console"].append(f"[{msg.type}] {msg.text}"))
    page.on("requestfailed", lambda request: logs["network_errors"].append(
        f"URL: {request.url} | Error: {request.failure.error_text if request.failure else 'Unknown error'}"
    ))
    page.on("response", lambda response: logs["network_errors"].append(
        f"URL: {response.url} | Status: {response.status}"
    ) if response.status >= 400 else None)
    yield logs

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin("html")
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, "extra", [])

    if report.when == "call":
        # Determine category based on markers
        category = "General"
        if item.get_closest_marker("smoke"): category = "🔥 Smoke"
        elif item.get_closest_marker("regression"): category = "🔄 Regression"
        elif item.get_closest_marker("security"): category = "🛡️ Security"
        elif item.get_closest_marker("api"): category = "📡 API"
        
        # Add Category to report metadata
        extra.append(pytest_html.extras.text(f"Category: {category}"))

        if report.failed:
            # 1. POC Capture
            page = item.funcargs.get("page")
            if page:
                screenshot_dir = "reports/screenshots"
                os.makedirs(screenshot_dir, exist_ok=True)
                file_name = f"{item.name}.png"
                page.screenshot(path=os.path.join(screenshot_dir, file_name))
                extra.append(pytest_html.extras.html(
                    f'<div style="margin:10px 0;"><b>📸 Visual Proof (POC):</b><br>'
                    f'<img src="screenshots/{file_name}" style="width:500px;border:3px solid #ff4d4d;border-radius:8px;" onclick="window.open(this.src)"></div>'
                ))

            # 2. AI Failure Diagnosis
            logs = item.funcargs.get("capture_logs", {"console": [], "network_errors": []})
            error_details = str(report.longreprtext)
            combined_context = f"Console: {logs['console']}\nNetwork: {logs['network_errors']}"
            ai_report = ai_service.analyze_failure(None, combined_context, error_details)
            
            # High-impact AI Box
            ai_box = f"""
            <div style="background: linear-gradient(135deg, #6e8efb, #a777e3); color: white; padding: 20px; border-radius: 12px; margin: 20px 0; box-shadow: 0 4px 15px rgba(0,0,0,0.2);">
                <h3 style="margin-top: 0; display: flex; align-items: center;">🤖 AI Autonomous QA Engineer - Diagnosis</h3>
                <hr style="border: 0; border-top: 1px solid rgba(255,255,255,0.3); margin: 10px 0;">
                <div style="font-size: 15px; line-height: 1.6;">
                    {ai_report.replace('\n', '<br>')}
                </div>
                <div style="margin-top: 15px; font-size: 12px; opacity: 0.8; font-style: italic;">
                    * This analysis was generated autonomously by analyzing browser traces, network traffic, and DOM state.
                </div>
            </div>
            """
            extra.append(pytest_html.extras.html(ai_box))

            # 3. Technical Audit
            audit_html = f"""
            <div style="background: #fdf2f2; border-left: 5px solid #f87171; padding: 15px; margin: 10px 0;">
                <b style="color: #991b1b;">🌐 Technical Audit Logs:</b>
                <pre style="white-space: pre-wrap; font-size: 11px;">{"".join(logs['console'][-10:]) or "No console logs."}</pre>
                <hr>
                <b style="color: #991b1b;">📡 Network Failures:</b>
                <pre style="white-space: pre-wrap; font-size: 11px; color: #dc2626;">{"".join(logs['network_errors']) or "No network errors."}</pre>
            </div>
            """
            extra.append(pytest_html.extras.html(audit_html))

    report.extra = extra

def pytest_html_report_title(report):
    report.title = "🎯 AI-Powered Quality Assurance Intelligence Report"

def pytest_html_results_summary(prefix, summary, postfix):
    prefix.extend([
        """
        <div style="background: #f0fdf4; border: 1px solid #bbf7d0; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h2 style="color: #166534; margin-top: 0;">✅ Executive Summary</h2>
            <p>This report was generated by the <b>Antigravity AI Automation Engine</b>. It combines Playwright browser automation with local <b>TinyLlama AI</b> to provide not just results, but deep technical investigations into every failure.</p>
            <ul style="color: #166534; font-weight: bold;">
                <li>🟢 Green: Passed - Feature is stable</li>
                <li>🔴 Red: Failed - AI Investigation attached</li>
                <li>🟡 Yellow: Warning - Environment/Network issues detected</li>
            </ul>
        </div>
        """
    ])

def pytest_configure(config):
    config._metadata['AI Engine'] = 'Active (Local TinyLlama)'
    config._metadata['Autonomous Level'] = 'Level 3 - Diagnostic'
