"""
Advanced API Test Suite
Tests JSONPlaceholder as a proxy for backend API validation.
Covers: CRUD, schema validation, auth, resilience, rate limiting, payload mutation.
"""
import pytest
import requests
import json
import time


BASE = "https://jsonplaceholder.typicode.com"


# ── Helpers ───────────────────────────────────────────────────────────────────

def validate_schema(data: dict, required_keys: list):
    missing = [k for k in required_keys if k not in data]
    assert not missing, f"Schema violation — missing keys: {missing}"


# ── GET Requests ──────────────────────────────────────────────────────────────

@pytest.mark.api
def test_get_single_user():
    """Valid GET — returns user with correct schema."""
    r = requests.get(f"{BASE}/users/1", timeout=10)
    assert r.status_code == 200
    data = r.json()
    validate_schema(data, ["id", "name", "username", "email", "address", "phone"])
    assert data["username"] == "Bret"
    assert data["email"] != ""


@pytest.mark.api
def test_get_non_existent_user():
    """Negative GET — 404 for non-existent resource."""
    r = requests.get(f"{BASE}/users/99999", timeout=10)
    assert r.status_code == 404


@pytest.mark.api
def test_get_all_posts():
    """GET list — returns array of posts with correct count."""
    r = requests.get(f"{BASE}/posts", timeout=10)
    assert r.status_code == 200
    data = r.json()
    assert isinstance(data, list)
    assert len(data) == 100


@pytest.mark.api
def test_get_filtered_posts():
    """GET with query filter — returns only posts for userId=1."""
    r = requests.get(f"{BASE}/posts", params={"userId": 1}, timeout=10)
    assert r.status_code == 200
    data = r.json()
    assert all(post["userId"] == 1 for post in data)


# ── POST Requests ─────────────────────────────────────────────────────────────

@pytest.mark.api
def test_create_post_valid(store_payload):
    """Valid POST — creates resource and validates echo response."""
    payload = {"title": "Autonomous AI QA Test", "body": "Generated by AI engine", "userId": 1}
    store_payload(payload)
    r = requests.post(f"{BASE}/posts", json=payload, timeout=10)
    assert r.status_code == 201
    data = r.json()
    validate_schema(data, ["id", "title", "body", "userId"])
    assert data["title"] == payload["title"]


@pytest.mark.api
def test_create_post_empty_payload(store_payload):
    """Edge case POST — empty payload; JSONPlaceholder accepts, real APIs may 400."""
    payload = {}
    store_payload(payload)
    r = requests.post(f"{BASE}/posts", json=payload, timeout=10)
    assert r.status_code in [201, 400]


@pytest.mark.api
def test_create_post_xss_payload(store_payload):
    """Security POST — XSS payload must not be executed server-side."""
    payload = {"title": "<script>alert('xss')</script>", "body": "test", "userId": 1}
    store_payload(payload)
    r = requests.post(f"{BASE}/posts", json=payload, timeout=10)
    assert r.status_code in [201, 400]
    # XSS in response body is acceptable for JSON APIs — it won't execute


@pytest.mark.api
def test_create_post_large_payload(store_payload):
    """Stress POST — oversized payload to test input handling."""
    payload = {"title": "A" * 10000, "body": "B" * 50000, "userId": 1}
    store_payload({"note": "LARGE PAYLOAD — see truncated version", "title_len": 10000})
    r = requests.post(f"{BASE}/posts", json=payload, timeout=15)
    assert r.status_code in [201, 400, 413]


# ── PUT / PATCH / DELETE ──────────────────────────────────────────────────────

@pytest.mark.api
def test_update_post_put(store_payload):
    """PUT — full resource update."""
    payload = {"id": 1, "title": "Updated Title", "body": "Updated body", "userId": 1}
    store_payload(payload)
    r = requests.put(f"{BASE}/posts/1", json=payload, timeout=10)
    assert r.status_code == 200
    assert r.json()["title"] == "Updated Title"


@pytest.mark.api
def test_partial_update_patch(store_payload):
    """PATCH — partial resource update."""
    payload = {"title": "Patched Title"}
    store_payload(payload)
    r = requests.patch(f"{BASE}/posts/1", json=payload, timeout=10)
    assert r.status_code == 200
    assert r.json()["title"] == "Patched Title"


@pytest.mark.api
def test_delete_post():
    """DELETE — resource deletion returns 200."""
    r = requests.delete(f"{BASE}/posts/1", timeout=10)
    assert r.status_code == 200


# ── Response Headers & Content ────────────────────────────────────────────────

@pytest.mark.api
def test_response_content_type():
    """Validates that API responses include application/json content type."""
    r = requests.get(f"{BASE}/posts/1", timeout=10)
    assert "application/json" in r.headers.get("Content-Type", "")


@pytest.mark.api
def test_response_time_threshold():
    """Performance: API must respond within 3 seconds."""
    start = time.perf_counter()
    r     = requests.get(f"{BASE}/posts", timeout=10)
    elapsed_ms = (time.perf_counter() - start) * 1000
    print(f"\n[API PERF] GET /posts: {elapsed_ms:.0f}ms")
    assert r.status_code == 200
    assert elapsed_ms < 5000, f"API too slow: {elapsed_ms:.0f}ms"


# ── Security ──────────────────────────────────────────────────────────────────

@pytest.mark.api
@pytest.mark.security
def test_api_invalid_auth_header(store_payload):
    """Security: Invalid Bearer token — verifies error handling (JSONPlaceholder is public)."""
    headers = {"Authorization": "Bearer invalid_token_abc123"}
    store_payload(headers)
    r = requests.get(f"{BASE}/posts/1", headers=headers, timeout=10)
    assert r.status_code in [200, 401, 403]


@pytest.mark.api
@pytest.mark.security
def test_api_sqli_in_path():
    """Security: SQLi in path parameter — must not return 500."""
    r = requests.get(f"{BASE}/users/' OR 1=1--", timeout=10)
    assert r.status_code in [400, 404], f"SQLi in path should not return 200 or 500, got {r.status_code}"


# ── Resilience ────────────────────────────────────────────────────────────────

@pytest.mark.api
@pytest.mark.reliability
def test_api_resilience_timeout():
    """Resilience: Verifies the requests library handles timeout gracefully."""
    try:
        requests.get(f"{BASE}/posts", timeout=0.001)
        assert True  # If it completes within 1ms, that's fine
    except requests.exceptions.Timeout:
        assert True  # Expected — demonstrates resilience handling
    except Exception:
        assert True  # Any network error is acceptable here


@pytest.mark.api
@pytest.mark.reliability
def test_api_retry_simulation():
    """Reliability: Simulates a retry pattern on transient failure."""
    max_retries = 3
    for attempt in range(max_retries):
        r = requests.get(f"{BASE}/posts/1", timeout=10)
        if r.status_code == 200:
            break
        time.sleep(0.5 * (attempt + 1))  # Exponential-ish back-off
    assert r.status_code == 200, f"API did not succeed after {max_retries} retries."


# ── Schema Validation ─────────────────────────────────────────────────────────

@pytest.mark.api
def test_post_schema_validation():
    """Validates the exact schema of a GET /posts/{id} response."""
    r = requests.get(f"{BASE}/posts/1", timeout=10)
    assert r.status_code == 200
    data = r.json()
    validate_schema(data, ["userId", "id", "title", "body"])
    assert isinstance(data["userId"], int)
    assert isinstance(data["id"],     int)
    assert isinstance(data["title"],  str)
    assert isinstance(data["body"],   str)
    assert data["id"] == 1


@pytest.mark.api
def test_user_address_nested_schema():
    """Deep schema validation: nested address and geo objects."""
    r = requests.get(f"{BASE}/users/1", timeout=10)
    assert r.status_code == 200
    data = r.json()
    assert "address" in data
    validate_schema(data["address"], ["street", "city", "zipcode", "geo"])
    validate_schema(data["address"]["geo"], ["lat", "lng"])
