"""
State Transition & Boundary Value Test Suite
Generated by the AI Dynamic Test Engine.
Covers: Cart state transitions, filter state machine, checkout state machine,
        boundary values for all input fields.
"""
import pytest
from playwright.sync_api import Page
from pages.login_page import LoginPage
from pages.inventory_page import InventoryPage
from pages.checkout_pages import CartPage, CheckoutStepOne, CheckoutStepTwo, CheckoutComplete
from utils.test_data_generator import TestDataGenerator


def _authenticated(page: Page) -> InventoryPage:
    """Helper: login and return InventoryPage."""
    login = LoginPage(page)
    login.navigate("https://www.saucedemo.com/")
    login.login("standard_user", "secret_sauce")
    return InventoryPage(page)


# ── State Transition: Cart Badge ──────────────────────────────────────────────

@pytest.mark.state_transition
@pytest.mark.ai_generated
def test_cart_badge_add_remove_cycle(page: Page):
    """
    State machine: EMPTY -> 1 item -> 2 items -> remove 1 -> remove all -> EMPTY
    Verifies badge counter accurately tracks every transition.
    """
    inv = _authenticated(page)

    # State 0: empty
    assert not page.is_visible(".shopping_cart_badge"), "Cart badge must not be visible on empty cart."

    # State 1: add first item
    inv.add_to_cart("Sauce Labs Backpack")
    assert page.inner_text(".shopping_cart_badge") == "1", "Badge must show 1."

    # State 2: add second item
    inv.add_to_cart("Sauce Labs Bike Light")
    assert page.inner_text(".shopping_cart_badge") == "2", "Badge must show 2."

    # State 3: remove first item
    inv.remove_from_cart("Sauce Labs Backpack")
    assert page.inner_text(".shopping_cart_badge") == "1", "Badge must show 1 after remove."

    # State 4: remove last item — badge disappears
    inv.remove_from_cart("Sauce Labs Bike Light")
    assert not page.is_visible(".shopping_cart_badge"), "Badge must disappear on empty cart."


@pytest.mark.state_transition
@pytest.mark.ai_generated
def test_cart_persists_across_sort_changes(page: Page):
    """Cart contents must survive sort order changes."""
    inv = _authenticated(page)
    inv.add_to_cart("Sauce Labs Backpack")

    for sort_val in ["az", "za", "lohi", "hilo"]:
        inv.change_sort(sort_val)
        assert page.inner_text(".shopping_cart_badge") == "1", (
            f"Cart badge lost after sorting by '{sort_val}'."
        )


# ── State Transition: Sort Filter ─────────────────────────────────────────────

@pytest.mark.state_transition
@pytest.mark.ai_generated
@pytest.mark.parametrize("sort_val, description", [
    ("az",   "Name A to Z"),
    ("za",   "Name Z to A"),
    ("lohi", "Price Low to High"),
    ("hilo", "Price High to Low"),
])
def test_sort_filter_state_transitions(page: Page, sort_val, description):
    """Each sort state must produce a valid (non-empty) product listing."""
    inv = _authenticated(page)
    inv.change_sort(sort_val)
    assert page.is_visible(".inventory_list"), f"Inventory must remain visible after sort '{description}'."
    items = page.locator(".inventory_item").count()
    assert items > 0, f"No products shown after sort '{description}'."


# ── State Transition: Checkout Flow ──────────────────────────────────────────

@pytest.mark.state_transition
@pytest.mark.ai_generated
def test_checkout_state_machine_complete(page: Page):
    """
    Full checkout state machine:
    Login -> Add -> Cart -> Checkout Step 1 -> Step 2 -> Complete
    """
    inv      = _authenticated(page)
    cart     = CartPage(page)
    step_one = CheckoutStepOne(page)
    step_two = CheckoutStepTwo(page)
    complete = CheckoutComplete(page)

    inv.add_to_cart("Sauce Labs Backpack")
    inv.go_to_cart()
    assert "cart.html" in page.url

    cart.click_checkout()
    assert "checkout-step-one" in page.url

    step_one.fill_form("AI", "QA", "99999")
    assert "checkout-step-two" in page.url

    step_two.click_finish()
    assert "checkout-complete" in page.url

    msg = complete.get_success_message()
    assert "Thank you" in msg, f"Expected thank-you message, got: {msg}"


@pytest.mark.state_transition
@pytest.mark.ai_generated
def test_checkout_back_navigation_preserves_cart(page: Page):
    """Back-navigating from checkout step 1 must preserve cart contents."""
    inv      = _authenticated(page)
    cart     = CartPage(page)
    step_one = CheckoutStepOne(page)

    inv.add_to_cart("Sauce Labs Backpack")
    inv.go_to_cart()
    cart.click_checkout()
    assert "checkout-step-one" in page.url

    page.click("id=cancel")
    assert "cart.html" in page.url
    assert "Sauce Labs Backpack" in page.inner_text(".cart_list"), (
        "Cart item must persist after cancelling checkout."
    )


# ── Boundary Value Tests ──────────────────────────────────────────────────────

@pytest.mark.boundary
@pytest.mark.ai_generated
@pytest.mark.parametrize("scenario, first, last, zip_code, expect_error", [
    ("empty_all",        "",             "",            "",          True),
    ("empty_zip_only",   "John",         "Doe",         "",          True),
    ("empty_first_only", "",             "Doe",         "12345",     True),
    ("max_length",       "A" * 50,       "B" * 50,      "99999",     False),
    ("single_char",      "A",            "B",           "1",         False),
    ("numeric_names",    "123",          "456",         "12345",     False),
    ("unicode_zip",      "John",         "Doe",         "郵便番号",  False),
    ("special_chars",    "O'Brien",      "Von Trapp",   "SW1A 1AA",  False),
    ("xss_first_name",   "<b>XSS</b>",  "Doe",         "12345",     False),
    ("negative_zip",     "John",         "Doe",         "-1",         False),
])
def test_checkout_boundary_values(page: Page, scenario, first, last, zip_code, expect_error):
    """AI-generated boundary and edge-case tests for the checkout form."""
    inv      = _authenticated(page)
    step_one = CheckoutStepOne(page)

    inv.add_to_cart("Sauce Labs Backpack")
    inv.go_to_cart()
    page.click("id=checkout")

    step_one.fill_form(first, last, zip_code)

    if expect_error:
        assert page.is_visible("h3[data-test='error']"), (
            f"Scenario '{scenario}': Expected validation error but none shown."
        )
    else:
        assert "checkout-step-two" in page.url or page.is_visible("h3[data-test='error']"), (
            f"Scenario '{scenario}': Unexpected page state: {page.url}"
        )


# ── Boundary: Login Fields ────────────────────────────────────────────────────

@pytest.mark.boundary
@pytest.mark.ai_generated
@pytest.mark.parametrize("username, password, description", [
    ("standard_user", "secret_sauce",  "exact valid credentials"),
    ("u" * 255,       "secret_sauce",  "max-length username"),
    ("standard_user", "p" * 255,       "max-length password"),
    ("u" * 256,       "p" * 256,       "over-max-length both fields"),
])
def test_login_boundary_values(page: Page, username, password, description):
    """Verifies login form handles boundary-length inputs gracefully (no crash)."""
    login = LoginPage(page)
    login.navigate("https://www.saucedemo.com/")
    login.login(username, password)
    # No hard assertion — we verify the page did not crash/throw a 500
    assert page.url is not None, f"Page crashed on '{description}'."
    assert "saucedemo.com" in page.url, f"Navigated away from site on '{description}'."
