import pytest
from pages.login_page import LoginPage
from pages.inventory_page import InventoryPage
from pages.checkout_pages import CheckoutStepOne

@pytest.mark.automation
@pytest.mark.ai_generated
class TestAIGeneratedScenarios:
    """
    These test cases were brainstormed and generated by the Autonomous AI Engine
    based on the existing Saucedemo Page Objects and Business Logic.
    """

    @pytest.mark.parametrize("scenario, username, password, expected_msg", [
        ("Exploratory: SQLi Attempt", "' OR '1'='1", "password", "Username and password do not match"),
        ("Edge: Buffer Overflow Name", "A" * 1000, "secret_sauce", "Products"),
        ("Security: Script Injection", "<script>alert('xss')</script>", "secret_sauce", "Username and password do not match"),
        ("Negative: Space-only Username", "   ", "   ", "Username is required"),
        ("Boundary: Unicode Pass", "standard_user", "密码123", "Username and password do not match")
    ])
    def test_ai_login_discoveries(self, page, scenario, username, password, expected_msg):
        """AI-Generated Scenarios for Login Resilience."""
        login_page = LoginPage(page)
        login_page.navigate("https://www.saucedemo.com/")
        login_page.login(username, password)
        
        if "match" in expected_msg or "required" in expected_msg:
            assert expected_msg in page.inner_text("h3[data-test='error']")
        else:
            inventory_page = InventoryPage(page)
            assert inventory_page.is_visible(inventory_page.header_title)

    @pytest.mark.parametrize("scenario, first, last, zip", [
        ("Boundary: Empty Checkout", "", "", ""),
        ("Edge: Multi-Byte Zip", "John", "Doe", "郵便番号"),
        ("Security: XSS in Address", "<b>John</b>", "Doe", "90210"),
        ("Negative: Numeric Fields", "12345", "67890", "ABCDE")
    ])
    def test_ai_checkout_data_mutation(self, page, scenario, first, last, zip):
        """AI-Generated Test Data Mutations for Checkout Flow."""
        login_page = LoginPage(page)
        inventory_page = InventoryPage(page)
        checkout_one = CheckoutStepOne(page)
        
        login_page.navigate("https://www.saucedemo.com/")
        login_page.login("standard_user", "secret_sauce")
        inventory_page.add_to_cart("Sauce Labs Backpack")
        inventory_page.go_to_cart()
        page.click("id=checkout")
        
        checkout_one.fill_form(first, last, zip)
        # AI Logic: Verify form state or errors
        assert page.is_visible("h3[data-test='error']") or "checkout-step-two" in page.url
